name: Pip.Services Facade toolkit in Node.js

on: 
  push:
    paths:
    - '**'
    - '!README.md'

jobs:
  Default:
    runs-on: ubuntu-16.04
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
    - uses: actions/checkout@main
  
    ############# Prepare #############

    - name: Install prereq and save build number
      id: build_info
      uses: pip-devops/actions/node/prepare@v1

    ############# Build and test #############

    - name: Build the component
      uses: pip-devops/actions/node/build@v1

    - name: Test the component
      uses: pip-devops/actions/node/test@v1

    ############# Release #############

    - name: Tag branch with the build number
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: "${{ steps.build_info.outputs.component_name }}/v${{ steps.build_info.outputs.component_version }}-${{ steps.build_info.outputs.build_number }}"

    - name: Release binary artifacts
      uses: pip-devops/actions/node/release@v1
      with:
        npm-user: ${{ secrets.NPM_USER }}
        npm-pass: ${{ secrets.NPM_PASS }}
        npm-email: ${{ secrets.NPM_EMAIL }}

    ############# Clear #############

    - name: Install prereq and save build number
      uses: pip-devops/actions/node/clear@v1
    